(in-package #:org.shirakumo.sf3)

(bs:define-io-structure model
  (format uint8)
  (material-type uint8)
  (material-size uint32)
  (textures (vector (string uint16) (ldb (byte 4 0) (bs:slot material-type))))
  (faces (vector uint32 uint32) :offset (+ (bs:slot material-size) 6))
  (vertices (vector float32 uint32)))

(defun vertex-attributes (model)
  (ecase (model-format model)
    (#x01 '(:position))
    (#x03 '(:position :uv))
    (#x05 '(:position :color))
    (#x09 '(:position :normal))
    (#x0B '(:position :uv :normal))
    (#x0D '(:position :color :normal))
    (#x1B '(:position :uv :normal :tangent))
    (#x1D '(:position :color :normal :tangent))))

(defun texture-types (model)
  (ecase (model-material-type model)
    (#x00 '())
    (#x01 '(:albedo))
    (#x03 '(:albedo :normal))
    (#x81 '(:albedo :emission))
    (#x43 '(:albedo :normal :specular))
    (#x83 '(:albedo :normal :emission))
    (#x07 '(:albedo :normal :metallic))
    (#x1B '(:albedo :normal :metalness :roughness))
    (#xC3 '(:albedo :normal :specular :emission))
    (#x87 '(:albedo :normal :metallic :emission))
    (#x9B '(:albedo :normal :metalness :roughness :emission))
    (#x3B '(:albedo :normal :metalness :roughness :occlusion))
    (#xBB '(:albedo :normal :metalness :roughness :occlusion :emission))))

(define-print-method model "~a ~d" (vertex-attributes object) (length (model-vertices object)))

(define-accessors model textures faces vertices)
