(defpackage #:org.shirakumo.sf3
  (:use #:cl #:org.shirakumo.binary-structures.types)
  (:shadow #:log #:read-line #:write-line #:time #:fill)
  (:local-nicknames
   (#:bs #:org.shirakumo.binary-structures)
   (#:bst #:org.shirakumo.binary-structures.types))
  ;; toolkit.lisp
  (:export
   #:unix-to-universal-time
   #:universal-time-to-unix)
  ;; archive.lisp
  (:export
   #:archive-meta-entry
   #:make-archive-meta-entry
   #:archive
   #:make-archive
   #:modification-time
   #:checksum
   #:mime-type
   #:path
   #:files
   #:add-file
   #:extract-file)
  ;; audio.lisp
  (:export
   #:audio
   #:make-audio
   #:duration
   #:samplerate
   #:channels
   #:sample-format
   #:samples)
  ;; image.lisp
  (:export
   #:image
   #:make-image
   #:pixel-type
   #:width
   #:height
   #:depth
   #:channels
   #:data)
  ;; log.lisp
  (:export
   #:log-entry
   #:make-log-entry
   #:log-chunk
   #:make-log-chunk
   #:log
   #:make-log
   #:size
   #:time
   #:severity
   #:source
   #:category
   #:message
   #:size
   #:entries
   #:start-time
   #:end-time
   #:chunks
   #:log
   #:log-append-chunk
   #:log-append-entry-extend)
  ;; model.lisp
  (:export
   #:model
   #:make-model
   #:vertex-attributes
   #:vertex-stride
   #:texture-types
   #:textures
   #:faces
   #:vertices)
  ;; physics-model.lisp
  (:export
   #:ellipsoid
   #:make-ellipsoid
   #:box
   #:make-box
   #:cylinder
   #:make-cylinder
   #:pill
   #:make-pill
   #:mesh
   #:make-mesh
   #:shape
   #:make-shape
   #:physics-model
   #:make-physics-model
   #:width
   #:height
   #:depth
   #:bottom-radius
   #:top-radius
   #:vertices
   #:transform
   #:data
   #:mass
   #:tensor
   #:shapes)
  ;; table.lisp
  (:export
   #:column-spec
   #:make-column-spec
   #:column-spec-type
   #:column-spec-element-size
   #:column-spec-element-count
   #:table
   #:make-table
   #:column-count
   #:row-count
   #:column-specs
   #:row-data
   #:row
   #:cell)
  ;; text.lisp
  (:export
   #:color-option
   #:make-color-option
   #:size-option
   #:make-size-option
   #:heading-option
   #:make-heading-option
   #:link-option
   #:make-link-option
   #:target-option
   #:make-target-option
   #:markup
   #:make-markup
   #:text
   #:make-text
   #:r
   #:g
   #:b
   #:size
   #:level
   #:address
   #:markup
   #:text)
  ;; vector-graphic.lisp
  (:export
   #:color
   #:make-color
   #:point
   #:make-point
   #:size
   #:make-size
   #:shape-fill
   #:make-shape-fill
   #:shape-bounds
   #:make-shape-bounds
   #:line
   #:make-line
   #:rectangle
   #:make-rectangle
   #:circle
   #:make-circle
   #:polygon
   #:make-polygon
   #:curve
   #:make-curve
   #:text-shape
   #:make-text-shape
   #:vector-graphic
   #:make-vector-graphic
   #:r
   #:g
   #:b
   #:a
   #:x
   #:y
   #:w
   #:h
   #:fill-color
   #:outline-color
   #:outline-thickness
   #:point
   #:size
   #:thickness
   #:color
   #:bounds
   #:fill
   #:points
   #:point
   #:color
   #:font
   #:font-size
   #:text
   #:width
   #:height
   #:instructions)
  ;; sf3.lisp
  (:export
   #:sf3-file-header
   #:make-sf3-file-header
   #:file-extension
   #:mime-type
   #:read-sf3
   #:write-sf3
   #:tell-sf3))
